# Lab 02. NumPy 배열에서 PyTorch Tensor로

> **One Lab, One Notebook**  
> 이 파일 하나가 GitHub(깃허브) 원본이자 Colab(코랩) 실습 파일입니다. Ubuntu(우분투)·VS Code(비에스 코드)에서도 같은 파일을 엽니다.

## 목표

- Python(파이썬) 리스트와 NumPy(넘파이) 배열의 차이 확인하기
- Scalar(스칼라, 값 1개)·Vector(벡터, 1차원 배열)·Matrix(매트릭스, 행렬) 구분하기
- NumPy 배열의 산술연산·브로드캐스팅·원소 접근 익히기
- PyTorch Tensor(파이토치 텐서, 다차원 배열) 만들기
- Tensor의 `dim`, `shape`, `dtype`, `device` 확인하기

아직 신경망 모델과 학습은 사용하지 않습니다.


## Setup

### 방법 1. Colab에서 실행

Colab에는 NumPy와 PyTorch가 기본 설치되어 있습니다. 위에서 아래로 `Shift + Enter`를 눌러 실행합니다.

### 방법 2. Ubuntu·VS Code에서 실행

가상환경을 만든 후 필요한 라이브러리를 설치합니다.

```bash
# 가상환경 생성
python3 -m venv .venv

# 가상환경 활성화
source .venv/bin/activate

# NumPy·PyTorch·Jupyter 설치
python -m pip install numpy torch jupyter
```

VS Code에서 이 파일을 열고 오른쪽 위의 `커널 선택`에서 `.venv`를 선택합니다.


## Steps

### 1. NumPy와 PyTorch 불러오기


In [1]:
import numpy as np
import torch

print("NumPy 버전:", np.__version__)
print("PyTorch 버전:", torch.__version__)
print("GPU 사용 가능:", torch.cuda.is_available())


NumPy 버전: 2.0.2
PyTorch 버전: 2.11.0+cpu
GPU 사용 가능: False


### 2. Python 리스트와 NumPy 배열 비교

Python 리스트의 `+`는 두 리스트를 이어 붙입니다. NumPy 배열의 `+`는 같은 위치의 원소끼리 더합니다.

> **A NumPy array performs numerical operations element by element.**  
> **NumPy 배열은 같은 위치의 원소별로 수치 연산을 수행합니다.**


In [2]:
python_list_a = [1.0, 2.0, 3.0]
python_list_b = [2.0, 4.0, 6.0]

numpy_array_a = np.array([1.0, 2.0, 3.0])
numpy_array_b = np.array([2.0, 4.0, 6.0])

print("Python 리스트 + :", python_list_a + python_list_b)
print("NumPy 배열 + :", numpy_array_a + numpy_array_b)
print("배열 자료형:", type(numpy_array_a))


Python 리스트 + : [1.0, 2.0, 3.0, 2.0, 4.0, 6.0]
NumPy 배열 + : [3. 6. 9.]
배열 자료형: <class 'numpy.ndarray'>


### 3. NumPy 배열의 산술연산

Element-wise operation(엘리먼트 와이즈 오퍼레이션, 원소별 연산)은 같은 위치의 원소끼리 계산합니다.


In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print("덧셈:", x + y)
print("뺄셈:", x - y)
print("원소별 곱셈:", x * y)
print("원소별 나눗셈:", x / y)
print("스칼라 나눗셈:", x / 2.0)


덧셈: [3. 6. 9.]
뺄셈: [-1. -2. -3.]
원소별 곱셈: [ 2.  8. 18.]
원소별 나눗셈: [0.5 0.5 0.5]
스칼라 나눗셈: [0.5 1.  1.5]


### 4. Scalar·Vector·Matrix 구분

| 구분 | 의미 | NumPy 형상 예 |
|---|---|---|
| Scalar(스칼라) | 값 1개 | `()` |
| Vector(벡터) | 1차원 배열 | `(3,)` |
| Matrix(매트릭스) | 2차원 행렬 | `(2, 2)` |
| Tensor(텐서) | 위 구조를 포함하는 다차원 배열 | `(2, 3, 4)` 등 |

`ndim`은 차원의 개수이고, `shape`는 각 차원의 크기입니다.


In [4]:
scalar_np = np.array(7)
vector_np = np.array([1, 2, 3])
matrix_np = np.array([[1, 2], [3, 4]])

for name, value in [
    ("Scalar", scalar_np),
    ("Vector", vector_np),
    ("Matrix", matrix_np),
]:
    print(f"{name:6} → ndim: {value.ndim}, shape: {value.shape}")


Scalar → ndim: 0, shape: ()
Vector → ndim: 1, shape: (3,)
Matrix → ndim: 2, shape: (2, 2)


### 5. NumPy N차원 배열과 속성

2차원 배열에서 바깥쪽 대괄호는 행의 묶음이고, 안쪽 대괄호 하나가 한 행입니다.


In [5]:
A = np.array([[1, 2], [3, 4]])

print(A)
print("차원 수:", A.ndim)
print("형상:", A.shape)
print("원소 자료형:", A.dtype)


[[1 2]
 [3 4]]
차원 수: 2
형상: (2, 2)
원소 자료형: int64


### 6. 배열 연산과 Broadcasting

Broadcasting(브로드캐스팅, 작은 배열을 큰 배열의 형상에 맞춰 자동 확장하는 기능)을 사용하면 형상이 다른 배열도 일정한 규칙으로 계산할 수 있습니다.


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
row_scale = np.array([10, 20])

print("A + B")
print(A + B)

print("\nA * B: 원소별 곱셈")
print(A * B)

print("\nA * 10: 스칼라 브로드캐스팅")
print(A * 10)

print("\nA * [10, 20]: 행 방향 브로드캐스팅")
print(A * row_scale)


A + B
[[ 4  2]
 [ 3 10]]

A * B: 원소별 곱셈
[[ 3  0]
 [ 0 24]]

A * 10: 스칼라 브로드캐스팅
[[10 20]
 [30 40]]

A * [10, 20]: 행 방향 브로드캐스팅
[[10 40]
 [30 80]]


### 7. 원소 접근·평탄화·조건 선택

- Indexing(인덱싱, 위치로 원소 선택)
- Flatten(플래튼, 다차원 배열을 1차원으로 평탄화)
- Boolean Mask(불리언 마스크, 조건이 참인 원소 선택)


In [7]:
X = np.array([[51, 55], [14, 19], [0, 4]])

print("전체 배열")
print(X)
print("첫 번째 행:", X[0])
print("첫 번째 행의 두 번째 값:", X[0][1])

X_flat = X.flatten()
print("평탄화:", X_flat)
print("0·2·4번 원소:", X_flat[np.array([0, 2, 4])])
print("15 초과 여부:", X_flat > 15)
print("15 초과 값:", X_flat[X_flat > 15])


전체 배열
[[51 55]
 [14 19]
 [ 0  4]]
첫 번째 행: [51 55]
첫 번째 행의 두 번째 값: 55
평탄화: [51 55 14 19  0  4]
0·2·4번 원소: [51 14  0]
15 초과 여부: [ True  True False  True False False]
15 초과 값: [51 55 19]


### 8. PyTorch Tensor 만들기

Tensor(텐서)는 Scalar·Vector·Matrix와 그 이상의 다차원 배열을 모두 포함하는 표현입니다.

> **A tensor is a multidimensional array that can run on a CPU or GPU.**  
> **텐서는 CPU(씨피유) 또는 GPU(지피유)에서 연산할 수 있는 다차원 배열입니다.**


In [8]:
scalar = torch.tensor(7)
vector = torch.tensor([1.0, 2.0, 3.0])
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:")
print(matrix)


Scalar: tensor(7)
Vector: tensor([1., 2., 3.])
Matrix:
tensor([[1., 2.],
        [3., 4.]])


### 9. Tensor의 dim·shape·dtype·device

| 속성 | 읽기 | 의미 |
|---|---|---|
| `dim()` | 딤 | 차원의 개수 |
| `shape` | 셰이프 | 각 차원의 크기 |
| `dtype` | 디타입 | 원소의 자료형 |
| `device` | 디바이스 | 텐서가 저장된 CPU 또는 GPU |


In [9]:
sensor_tensor = torch.tensor(
    [[22.5, 0.10], [31.0, 0.45], [36.0, 0.90]],
    dtype=torch.float32,
)

print(sensor_tensor)
print("dim:", sensor_tensor.dim())
print("shape:", sensor_tensor.shape)
print("dtype:", sensor_tensor.dtype)
print("device:", sensor_tensor.device)


tensor([[22.5000,  0.1000],
        [31.0000,  0.4500],
        [36.0000,  0.9000]])
dim: 2
shape: torch.Size([3, 2])
dtype: torch.float32
device: cpu


### 10. NumPy 배열과 Tensor 변환

NumPy 배열은 `torch.from_numpy()`로 Tensor로 바꿀 수 있고, CPU Tensor는 `.numpy()`로 NumPy 배열로 바꿀 수 있습니다.


In [10]:
numpy_data = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)
tensor_data = torch.from_numpy(numpy_data)
numpy_again = tensor_data.numpy()

print("NumPy → Tensor")
print(tensor_data)
print("Tensor → NumPy")
print(numpy_again)


NumPy → Tensor
tensor([[1., 2.],
        [3., 4.]])
Tensor → NumPy
[[1. 2.]
 [3. 4.]]


### 11. Tensor의 device 선택

GPU가 있으면 CUDA(쿠다, 엔비디아 GPU 병렬 연산 플랫폼)를 선택하고, 없으면 CPU를 사용합니다. Colab의 런타임에서 GPU를 선택하면 같은 코드가 자동으로 GPU를 사용합니다.


In [11]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_on_device = sensor_tensor.to(device)

print("선택된 device:", device)
print("Tensor의 실제 device:", tensor_on_device.device)


선택된 device: cpu
Tensor의 실제 device: cpu


## Practice

아래 코드에서 `TODO` 네 곳을 수정합니다.

1. 온도와 진동으로 구성된 3×2 NumPy 배열 만들기
2. NumPy 배열의 `shape` 확인하기
3. NumPy 배열을 Tensor로 변환하기
4. Tensor의 `dim`, `shape`, `dtype`, `device` 출력하기


In [12]:
# TODO 1: 온도와 진동 데이터 3건을 입력합니다.
practice_array = np.array(
    [[20.0, 0.10], [30.0, 0.40], [40.0, 0.80]],
    dtype=np.float32,
)

# TODO 2: shape를 출력합니다.
print("NumPy shape:", practice_array.shape)

# TODO 3: NumPy 배열을 Tensor로 변환합니다.
practice_tensor = torch.from_numpy(practice_array)

# TODO 4: Tensor의 핵심 속성을 출력합니다.
print("Tensor dim:", practice_tensor.dim())
print("Tensor shape:", practice_tensor.shape)
print("Tensor dtype:", practice_tensor.dtype)
print("Tensor device:", practice_tensor.device)


NumPy shape: (3, 2)
Tensor dim: 2
Tensor shape: torch.Size([3, 2])
Tensor dtype: torch.float32
Tensor device: cpu


## Checks

아래 셀에서 오류가 없으면 Lab 02가 정상적으로 완료된 것입니다.


In [13]:
assert numpy_array_a.shape == (3,)
assert matrix_np.ndim == 2
assert A.shape == (2, 2)
assert X_flat.tolist() == [51, 55, 14, 19, 0, 4]
assert sensor_tensor.dim() == 2
assert tuple(sensor_tensor.shape) == (3, 2)
assert sensor_tensor.dtype == torch.float32
assert torch.equal(torch.from_numpy(numpy_data), tensor_data)

print("Lab 02 실행 확인 완료")


Lab 02 실행 확인 완료


## Next Steps

다음 주제는 새 노트북 `Lab_03_Tensor_Operations.ipynb`로 진행합니다.

- Tensor 생성 함수: `zeros`, `ones`, `arange`, `rand`
- Indexing(인덱싱)·Slicing(슬라이싱)
- `reshape`, `view`, `squeeze`, `unsqueeze`
- Element-wise Product(엘리먼트 와이즈 프로덕트, 원소별 곱)와 Matrix Multiplication(매트릭스 멀티플리케이션, 행렬곱)
